== Data Model

TODO one sentence

=== Requirements Class "Data Model"

==== Overview

This Requirements Class provides requirements for the Data Model.

include::../requirements/requirements_class_data-model.adoc[]

==== FirstMileMessage

A FirstMileMessage message denotes whether the content describes data or metadata.

include::../requirements/data-model/REQ_first_mile_message.adoc[]

==== Location

A Location message defines the geospatial location of a given ObserverDevice or Node.

include::../requirements/data-model/REQ_location.adoc[]

==== Metadata

A Metadata message defines the observers and parameters defined at a given Node.  It also defines a namespace map for parameter definitions using existing controlled vocabularies.

include::../requirements/data-model/REQ_metadata.adoc[]

==== Metadata.Node

A Node message describes the devices defines the data capture and transmits the data.

include::../requirements/data-model/REQ_node.adoc[]
include::../recommendations/data-model/REC_node.adoc[]
include::../recommendations/data-model/PER_node.adoc[]

==== Metadata.ObserverDevice

An ObserverDevice message describes individual devices connected to Node.

include::../requirements/data-model/REQ_observer_device.adoc[]
include::../recommendations/data-model/REC_observer_device.adoc[]
include::../recommendations/data-model/PER_observer_device.adoc[]

==== Metadata.ParameterDefinition

A ParameterDefinition message describes a set of variables or measurement types.

include::../requirements/data-model/REQ_parameter_definition.adoc[]

==== Metadata.ParameterDefinition.Parameter

A Parameter message describes single variable or measurement type.

include::../requirements/data-model/REQ_parameter.adoc[]

==== Metadata.ParameterDefinition.Parameter.DeviceRef

A DeviceRef message describes a reference to an ObserverDevice message.

include::../requirements/data-model/REQ_device_ref.adoc[]

==== Data

A Data message provides the observations provided at a Node.

include::../requirements/data-model/REQ_data.adoc[]

==== Observation

An Observation message defines the values associated with parameter definitions provided at a Node.

include::../requirements/data-model/REQ_observation.adoc[]

==== Value

A Value message defines the measurement of data of different types.

include::../requirements/data-model/REQ_value.adoc[]
