name: validate schema and examples

on:
  push:
    paths:
      - '**.proto'
      - '**.textproto'
  pull_request:
    paths:
      - '**.proto'
      - '**.textproto'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v5
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies 📦
      run: |
        sudo apt-get install protobuf-compiler
    - name: Install requirements 📦
      run: |
        python3 -m pip install --upgrade pip
        pip3 install protobuf
    - name: Generate Python code
      run: |
        protoc --python_out=. schemas/first-mile-message-encoding.proto 
        mv schemas/first_mile_message_encoding_pb2.py scripts
    - name: Run validation
      run: |
        set +e
        num_errors=0

        for e in examples/*/*.textproto; do
          python3 scripts/validate.py $e || num_errors=$((num_errors + 1))
        done

        exit $num_errors
